name: .NET

on:
  workflow_dispatch:

jobs:
  build:
    uses: demoserievideo/pipeline-templates/dotnet-build.yml@main

#    runs-on: ubuntu-latest

    #steps:
    #- uses: actions/checkout@v2
    #- name: Setup .NET
    #  uses: actions/setup-dotnet@v1
    #  with:
    #    dotnet-version: 5.0.x
    #- name: Restore dependencies
    #  run: dotnet restore
    #- name: Build
    #  run: dotnet build --no-restore
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal

  deploy_dev:
    name: Deploy Dev
    runs-on: ubuntu-latest
    environment:
      name: dev 
    needs: build    
    steps:
    - run: |
        echo "Deploy Dev"

  deploy_hmg:
    name: Deploy HMG
    runs-on: ubuntu-latest
    environment:
      name: hmg 
    needs: deploy_dev    
    steps:
    - run: |
        echo "Deploy HMG"
